AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket, IAM user, and SQS queue for browser-quality audio uploads with presigned URLs and event notifications

Parameters:
  Env:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Resources:
  AudioUploadsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub waymark-audio-uploads-${Env}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - http://localhost:3000
            AllowedMethods:
              - PUT
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt BrowserQualityTranscodeQueue.Arn
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true

  AudioUploadsPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AudioUploadsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPublicReadProcessed
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::waymark-audio-uploads-${Env}/processed/*

  BrowserQualityTranscodeDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub browser-quality-transcode-dlq-${Env}

  BrowserQualityTranscodeQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub browser-quality-transcode-queue-${Env}
      VisibilityTimeout: 600 # 10 minutes for FFmpeg jobs
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt BrowserQualityTranscodeDLQ.Arn
        maxReceiveCount: 5

  BrowserQualityQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref BrowserQualityTranscodeQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt BrowserQualityTranscodeQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt AudioUploadsBucket.Arn

  AudioUploaderUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub audio-uploader-${Env}

  AudioUploaderPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub audio-uploader-s3-policy-${Env}
      Users:
        - !Ref AudioUploaderUser
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::waymark-audio-uploads-${Env}/uploads/*

  AudioUploaderAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref AudioUploaderUser

Outputs:
  AccessKeyId:
    Description: Access key for audio uploader
    Value: !Ref AudioUploaderAccessKey
    Export:
      Name: AudioUploaderAccessKeyId

  SecretAccessKey:
    Description: Secret access key for audio uploader
    Value: !GetAtt AudioUploaderAccessKey.SecretAccessKey
    Export:
      Name: AudioUploaderSecretAccessKey

  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref AudioUploadsBucket
    Export:
      Name: AudioUploadsBucketName
